"""Declarative base, shared mixins and the portable vector type.

Two things here are worth understanding before adding a model.

Tenancy: every table that belongs to a brand carries a ``brand_id``, even
where it could be reached through a join. That denormalisation is deliberate.
It lets one WHERE clause isolate a tenant, it lets PostgreSQL row level
security policies be written without recursive joins, and it makes the
isolation tests cheap to write. Multi tenant leaks are the one bug that would
end this business, so the schema pays a small normalisation price to make them
hard.

Portability: tests run on SQLite and production runs on PostgreSQL, so any
PostgreSQL only type is wrapped in a TypeDecorator that degrades sensibly.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from typing import Any

from sqlalchemy import DateTime, Integer, MetaData, String, func
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import DeclarativeBase, Mapped, declared_attr, mapped_column
from sqlalchemy.types import JSON, TypeDecorator

# Explicit naming so that autogenerated migrations produce stable, readable
# constraint names instead of database defaults that differ per engine.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    # JSON on SQLite, JSONB on PostgreSQL. Both annotation spellings are
    # mapped because the models use whichever reads better locally, and an
    # unmapped annotation is a confusing startup error rather than a warning.
    type_annotation_map = {
        dict[str, Any]: JSON().with_variant(postgresql.JSONB(), "postgresql"),
        dict[str, object]: JSON().with_variant(postgresql.JSONB(), "postgresql"),
        list[float]: JSON().with_variant(postgresql.JSONB(), "postgresql"),
    }


def utcnow() -> datetime:
    """Timezone aware now. Never use naive datetimes in this codebase."""
    return datetime.now(UTC)


def new_id() -> str:
    """Opaque primary key.

    UUID4 as a string rather than a serial integer, so that identifiers can be
    put in URLs and logs without leaking how many brands or orders exist, and
    so records can be created in a worker without a round trip to the database.
    """
    return str(uuid.uuid4())


class UUIDPrimaryKey:
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class SoftDeleteMixin:
    """Soft delete for anything a brand or an auditor may need to see again.

    Hard deletes are reserved for data protection requests. Everything else
    sets ``deleted_at`` so that an order still resolves to the lot it was
    placed against, even after the brand removes that lot.
    """

    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)

    @property
    def is_deleted(self) -> bool:
        return self.deleted_at is not None


class VersionMixin:
    """Optimistic locking.

    Lots and orders are edited by a brand, an admin and a background AI job at
    the same time. Without this, two concurrent writes silently discard one of
    the changes.
    """

    @declared_attr
    def version(cls) -> Mapped[int]:
        return mapped_column(Integer, nullable=False, default=1)

    __mapper_args__ = {"version_id_col": None}  # set per model, see catalog.py


class Vector(TypeDecorator[Any]):
    """Embedding column that works on PostgreSQL and on SQLite.

    On PostgreSQL this is a real ``pgvector`` column, so similarity search uses
    an index. On SQLite it falls back to JSON, which is enough for tests but
    cannot be searched efficiently. Phase 2 visual search therefore requires
    PostgreSQL, and the test suite asserts storage and retrieval only.
    """

    impl = JSON
    cache_ok = True

    def __init__(self, dim: int = 768) -> None:
        self.dim = dim
        super().__init__()

    def load_dialect_impl(self, dialect: Any) -> Any:
        if dialect.name == "postgresql":
            from pgvector.sqlalchemy import Vector as PgVector

            return dialect.type_descriptor(PgVector(self.dim))
        return dialect.type_descriptor(JSON())

    def process_bind_param(self, value: Any, dialect: Any) -> Any:
        if value is None:
            return None
        if dialect.name == "postgresql":
            return value
        return list(value)

    def process_result_value(self, value: Any, dialect: Any) -> Any:
        if value is None:
            return None
        return list(value)
